name:                localcooking-farm
version:             0.0.0
git:                 "git://git.localcooking.com/localcooking/localcooking-farm.git"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 (c) Local Cooking Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/athanclark/localcooking#readme>

dependencies:
- base >= 4.8 && < 5

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - localcooking-shared
    - localcooking-db
    - localcooking-template
    - aeson
    - attoparsec
    - attoparsec-uri
    - bytestring
    - emailaddress
    - file-embed
    - http-types
    - mtl
    - nested-routes >= 9.0.0.1
    - path
    - path-extra >= 0.2.0
    - shakespeare
    - sparrow >= 0.0.1.4
    - strict
    - QuickCheck
    - text
    - urlpath >= 9.0.0
    - wai-middleware-content-type >= 0.6.1.2
    - wai-transformers >= 0.1.0

executables:
  localcooking-farm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - localcooking-farm
    - localcooking-template

tests:
  localcooking-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - localcooking-farm
    - localcooking-db
    - localcooking-template
    - aeson
    - path-extra
    - tasty
    - tasty-quickcheck
